### ISSUE TITLE
Not working with macro tooltips

### ISSUE THREAD

**Issue by WanderingFox** [gi2k15/Caravana#3]
Firstly, thank you for this addon. It's incredibly handy :)

Unfortunately the fix from @zaazu doesn't seem to work with macro tooltips, even if you add a handler for macros. Looks like `GetSpell` doesn't return anything for macro tooltips :(

Posting mostly for visibility since I can't see a way to implement it for macros currently without scanning the tooltip text.

**Comment by Zaazu** [comment]
Hey, did it work before dragonflight? Can you paste the macro you're using and I'll take a look

**Comment by WanderingFox** [comment]
Sure!

```
#showtooltip
/cast [mod] Return To Camp; Timewalker's Hearthstone
```

Pre-dragonflight if you hovered over that macro while holding a modifier key you'd get the Return To Camp tooltip with the caravana line added (presumably because both spells and macros used the same GameTooltip). Now, with the latest version of caravana nothing happens (because it only adds a hook to spell tooltips). If you refactor it to add the same handler for macro tooltips as well, nothing happens either because the `_, SpellId = self:GetSpell()` line returns `nil`.

**Comment by Zaazu** [comment]
Couldn't figure out an elegant solution but atleast it should work for now. I ended up scanning the tooltip like you said, it's not pretty but for such a small addon, I don't think it'll cause problems.

**Comment by WanderingFox** [comment]
TY for this :)
